html-next/vertical-collection

- .travis.yml
- addon/-debug/edge-visualization/visualization.js
- addon/-debug/helpers.js
- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/index.js
- addon/-private/data-view/radar/static-radar.js
- addon/components/vertical-collection/component.js
- addon/components/vertical-collection/template.hbs
- bower.json
- config/changelog.js
- config/ember-try.js
- config/environment.js
- config/release.js
- ember-cli-build.js
- index.js
- package.json
- testem.js
- tests/dummy/app/routes/examples/infinite-scroll/controller.js
- tests/dummy/app/routes/examples/infinite-scroll/route.js
- tests/dummy/app/routes/examples/infinite-scroll/template.hbs
- tests/dummy/config/environment.js
- tests/helpers/wait.js
- tests/index.html
- tests/integration/components/vertical-collection-test.js
It turns out that `radar` needs to be a computed property in order to respond to array mutations. Something in the template itself has to be bound in order for radar to be recomputed, and as the only thing that is bound at all is `virtualComponents`, they needed to be moved into `radar` proper to put it on the refresh path.
> refactor(radar): Converts `radar` into a computed property

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/index.js
- addon/components/vertical-collection/component.js
Sometimes scrollTop can change between the time we schedule a RAF and the time
the RAF occurs, especially in Firefox. Removing the extra caching layer makes
it much easier to guarantee that everything is working correctly
> refactor(radar): Stop cacheing scrollTop

- addon/components/vertical-collection/component.js
Sending actions can trigger a lot of things, including more rendering. We should defer that work until after the RAF has finished.
> perf(actions): Defers action sending until after RAF

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/index.js
- addon/-private/data-view/radar/static-radar.js
- addon/-private/data-view/skip-list.js
- addon/-private/data-view/virtual-component.js
- addon/components/vertical-collection/component.js
- addon/components/vertical-collection/template.hbs
- tests/dummy/app/routes/examples/scrollable-body/template.hbs
- tests/dummy/app/styles/app.css
- tests/integration/measure-test.js
- tests/integration/modern-ember-test.js
This PR simplifies the current state management for measuring VCs. They no longer cache data   about their geometry or measure state. Additionally, it changes the logic surrounding measurement in general. We now measure in three phases:
1. We measure the all items just before we make any changes or measurements. This is to capture any possible changes that could have happened while items were rendered.
2. If necessary we measure the items that could affect the scroll position post-render (e.g. if we are scroll up). This occurs after the Radar's update phase (RAF 'measure').
3. We use `run.next` to defer a full measurement of all items until after the RAF, making sure the extra work doesn't block us.
There is also a minor perf improvement, we no longer add `_prependOffset` in the sync …
> refactor(measure): Simplifies measurement and only measures when necessary

- addon/-private/data-view/virtual-component.js
Edge can't reuse Ranges for some reason, probably a bug. It also can't use the `new Range()` style of creating a range.
> bugfix(edge): Fixes various issues with ranges in MS Edge

- addon/components/vertical-collection/component.js
- tests/integration/basic-test.js
Fixes a bug where setting a key path would cause failures due to isPrepend trying to get on a nonexistant item.
> bugfix(key): Fixes the key path

- addon/components/vertical-collection/component.js
- tests/dummy/app/routes/examples/dbmon/template.hbs
- tests/dummy/app/routes/examples/flexible-layout/template.hbs
- tests/dummy/app/routes/examples/infinite-scroll/template.hbs
- tests/dummy/app/routes/examples/reduce-debug/template.hbs
- tests/dummy/app/routes/examples/scrollable-body/template.hbs
- tests/integration/basic-test.js
- tests/integration/measure-test.js
- tests/integration/modern-ember-test.js
- tests/integration/mutation-test.js
- tests/integration/scroll-test.js
`alwaysRemeasure` is a vague API name that leaks internal implementation details.
`staticHeight` implies the reverse, and is more clear that the user is opting into
a perf optimization.
> refactor(api): Change alwaysRemeasure to staticHeight

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/index.js
- addon/-private/data-view/virtual-component.js
- addon/components/vertical-collection/component.js
Because of the setTimeout bug described in #31, we cannot reliably schedule using setTimeout/ run.next(). There are two places where this happens - 1st in the component itself when it schedules sending actions, and second in the DynamicRadar when it schedules a full measure. The full measure appears to be redundant, as another full measure will be done before any changes occur in the next scroll (per the change in measuring strategy to account for item height changes) and the action sending can be done in the RAF by scheduling on the current runloop (Todo: Add a perf notes/gotchas page in the docs to go over the implications of this design choice).
Also plugs some cancellation bugs that were probably causing the failures in #33.
Closes #31 and #33
> bugfix(scheduling): Moves all scheduling into the RAF and ensures proper cancelling

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/index.js
- addon/-private/data-view/virtual-component.js
- addon/components/vertical-collection/template.hbs
- ember-cli-build.js
- index.js
- tests/integration/mutation-test.js
Glimmer was messing up due to extra text nodes being inserted, had to remove those.
Also fixed the logic surrounding resetting collections (no state changes or measurements
should occur) and made VC moving a little cleaner.
Fixes #24
> refactor(reset): Fixes reset and shrinking logic

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/index.js
- addon/-private/data-view/utils/move-range.js
- addon/-private/data-view/virtual-component.js
- addon/components/vertical-collection/template.hbs
- tests/dummy/app/helpers/join-strings.js
- tests/helpers/array.js
- tests/integration/mutation-test.js
Turns out Glimmer 1 and 2 track their end nodes slightly differently, so we had to account for that. Glimmer 2 also doesn't seem to completely delete components if you empty an `each`. Caught a couple of small bugs as well.
> bugfix(reset): Fixes the case when a collection is emptied

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/index.js
- addon/-private/data-view/virtual-component.js
Don't double render, and don't create objects when we don't need to
> bugfix(render): Add correct items to VCs on initial render

- addon/-private/utils/element/closest.js
Allows us to keep our JS in `<HEAD>`.
> Make closest not require document.body

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/components/vertical-collection/component.js
- tests/integration/scroll-test.js
Fixes #52 and #70 
* Adds `firstReached` and `lastReached` key maps that track whether or not we've sent the first/last reached actions for an item. We need separate maps for the case where we have 1 item.
* Moves the handling sending items into the Radar class itself. This is a more natural fit place for the state to live, and it also opens up the door to further refactors in the `vertical-collection` component itself.
* Refactors action sending to schedule independently for each action. This means that if a user only has the `lastReached` action, we won't be using `setTimeout` every time the first/last visible items change, for instance.
* Adds extra properties in constructors to avoid thrashing prototypes
> refactor(actions): Makes sure first/lastReached fire only once

- .eslintrc.js
- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/skip-list.js
- tests/integration/measure-test.js
Uses Float32Arrays to get sub-pixel accuracy from measurements. Fixes #76
> bugfix(skiplist): Use Float32Arrays in the SkipList

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/-private/data-view/skip-list.js
- addon/-private/data-view/utils/scroll-handler.js
- addon/-private/data-view/virtual-component.js
- addon/-private/ember-internals/utils/key-for-item.js
- addon/-private/scheduler/index.js
- addon/-private/utils/element/apply-dimensions.js
- addon/-private/utils/element/closest.js
- addon/-private/utils/element/get-height.js
- addon/-private/utils/element/get-width.js
- addon/components/vertical-collection/component.js
- addon/components/vertical-collection/template.hbs
- config/ember-try.js
- tests/acceptance/acceptance-tests/record-array-test.js
- tests/dummy/app/routes/acceptance-tests/record-array/template.hbs
- tests/dummy/app/routes/examples/reduce-debug/template.hbs
- tests/integration/basic-test.js
This adds a (was failing) test for starting a dynamically sized list in a position offset from the top of the scroll-container.
However, this causes the skip-list to need to deal with negative numbers. To handle this, I then changed the determination of `middleVisibleValue` to:
```
let top = this.visibleTop;
if (top < 0) {
top = 0;
}
const middleVisibleValue = top + (this.scrollContainerHeight / 2);
```
> Fix dynamic start with offset

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/-private/data-view/skip-list.js
- addon/-private/data-view/virtual-component.js
- addon/-private/index.js
- addon/-private/scheduler/index.js
- addon/components/vertical-collection/component.js
- package.json
- tests/helpers/wait.js
- tests/integration/mutation-test.js
- tests/integration/scroll-test.js
- yarn.lock
This PR does a few things mostly centered around normalizing the `scheduleUpdate` function so that we are:
1. Deferring all work into a RAF, both so measurements are much lower cost and so we don't block the critical path to rendering
2. Always remeasuring so that the internal values we run against are always up to date (`scrollContainerHeight`, `scrollTopOffset`, etc).
3. Always updating everything, including the VC pool
It drops the confusing system of getters/setters for these values and replaces them with a pipeline where every stage of rendering is clearly defined and always happens at a specific point, giving us direct control over where and when we decide to measure and allowing us to prevent forced layouts much more easily.
Still working on this, I'd like to figure out a way to …
> [WIP] refactor(radar): startup and resize

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/components/vertical-collection/component.js
- tests/integration/measure-test.js
This PR fixes 3 bugs:
1. Deltas when scrolling up are now measured as floats, but `scrollTop` is only ever an integer, so we need to round them to make sure that when we compare the actual scrollTop of the container to our measured version they are the same.
2. When doing the first measure during a prepend, we used the `firstItemIndex` to set measured values in the skipList. This was incorrect because the prepend pushes items forward, so we need to use `_prevFirstItemIndex` instead (value that gets modified in a prepend).
3. When finding the item that matches `idForFirstItem`, we wouldn't iterate over the entire array, meaning if the id were for the last item it would not be found.
> bugfix(prepend): Fixes measuring when prepending items and scrolling up

- addon/components/vertical-collection/component.js
The ScrollHandler has to read the initial state of the scrollContainer (scrollTop + scrollLeft) to be able to know if a scroll event has actually caused a change. Doing that directly in `didInsertElement` will cause a forced layout, so it's a better idea to schedule it inside of the first RAF.
Timeline Before:
Timelines After:
> perf(initial render): Adds scroll handlers inside the initial RAF

- addon/-private/data-view/skip-list.js
Uses the same strategy as in Heimdall to polyfill `fill`: https://github.com/heimdalljs/heimdalljs-lib/blob/master/src/shared/array-fill.ts
Note the Heimdall uses TypedArrays' existence to determine whether or not `fill` should be used, but this doesn't appear to be correct. TypedArrays existed as far back as IE10, but none of the IE's support `fill`. Safari also has this issue.
> bugfix(ie): Array.prototype.fill doesn't exist in IE

- .travis.yml
- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/components/vertical-collection/component.js
- tests/integration/basic-test.js
Adds an `initialRenderCount` option which will render a static number of items on the first pass. This allows users to: 
A. Not take the initial perf hit on first render from rendering so many items inside of a RAF and
B. Specify a number to be rendered for things like Fastboot
Timelines before:
Timelines after:
> feature(init): Adds initialRenderCount option

- addon/-debug/edge-visualization/visualization.js
- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/-private/data-view/skip-list.js
- addon/components/vertical-collection/component.js
- addon/styles/app.css
- tests/acceptance/acceptance-tests/record-array-test.js
- tests/dummy/app/routes/acceptance-tests/record-array/template.hbs
- tests/dummy/app/routes/examples/dbmon/template.hbs
- tests/dummy/app/routes/examples/flexible-layout/template.hbs
- tests/dummy/app/routes/examples/infinite-scroll/controller.js
- tests/dummy/app/routes/examples/infinite-scroll/template.hbs
- tests/dummy/app/routes/examples/scrollable-body/template.hbs
- tests/dummy/app/routes/settings/snippets/defaults.js
- tests/helpers/test-scenarios.js
- tests/integration/basic-test.js
- tests/integration/measure-test.js
- tests/integration/modern-ember-test.js
- tests/integration/mutation-test.js
- tests/integration/scroll-test.js
Removes the minHeight constraint and replaces it with `estimateHeight`. Also makes the collection create VCs dynamically based on the size of the scrollContainer so the number of VCs will be minimized and able to adapt to a large number of items being under the `estimateHeight`.
Note: If there are a large number of items under the estimateHeight on initial render, they still won't span the scrollContainer immediately. This is kind of a catch-22 because in order to know how many VCs we need to render, we need to first render them and then measure them. We can attempt to progressively re-render until the scrollContainer is spanned, but for now I think the recommended solution would be to on average have item height be above the estimate, and if it can't be use larger buffers.
> refactor(minHeight): Removes minHeight constraints

- addon/-private/data-view/radar/radar.js
- tests/dummy/app/styles/app.css
- tests/integration/basic-test.js
Fixes the max height detection on scroll container. This means that if the scroll container has a max-height set, the collection will ignore the actual height and always render the max-height with the assumption that it must do so to fill out the container.
> bugfix(max-height): Use computed style to determine if max-height exists

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/components/vertical-collection/component.js
- tests/integration/basic-test.js
- tests/integration/recycle-test.js
Adds the `shouldRecycle` option which, when false, turns off component recycling. This may make sense for certain use cases, but it should be noted that in early testing this strategy is a major perf hit.
With recycling:
Without recycling:
> feat(recycling): Makes recycling optional

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/-private/data-view/skip-list.js
- tests/integration/basic-test.js
Cleans up radar by:
* Removing NULL_INDEX and replacing it with a reset flag. It was essentially implicitly tracking resets, so an explicit flag makes this behavior much clearer.
* Making `visibleTop` always 0 or great, getting rid of `visibleMiddle` and using the skip list to find the barriers always. No more while loops iterating around to find boundaries.
> chore(cleanup): clean up various parts of radar

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/-private/data-view/skip-list.js
- tests/helpers/test-scenarios.js
- tests/integration/basic-test.js
Adds labels in the `occluded-content` field which display how many items are above and below the rendered area, as well as pagination which will move the user forward/backward to the next/previous set of items when `occluded-content` is clicked. We will likely need to add ARIA roles or something to make it clear that `occluded-content` is clickable and meant for navigation.
> feature(a11y): Adds labels for occluded content and pagination

- addon/styles/app.css
Two fixes:
* `min-height` is used to prevent margin collapsing, but production builds will clear out the current value because it's too small.
* occluded a11y content can be visible if the user scrolls fast enough, this makes the text color transparent so it can still be read by screen readers but will be invisible otherwise.
> bugfix(css): Makes a11y text invisible and margin fix

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- index.js
- tests/acceptance/acceptance-tests/record-array-test.js
- tests/integration/basic-test.js
- tests/integration/measure-test.js
- tests/integration/mutation-test.js
- tests/integration/scroll-test.js
Dynamic pool size is nice, especially if users regularly have items under the `estimateHeight`, but the perf hit was pretty large. This reverts to the previous behavior with a stable component pool size. If users need more components to render, they can use a larger `bufferSize`.
> perf(pooling): Reverts to maintaining a stable pool size

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/skip-list.js
- addon/-private/utils/element/estimate-element-height.js
- tests/integration/basic-test.js
- tests/integration/measure-test.js
* Makes sure that the SkipList gets the correct estimate height
* Keeps measurement information when the SkipList is reset
> bugfix(skip-list): Fix skip-list reset and measurement behavior

- addon/-private/data-view/utils/object-at.js
We should only enforce that the array implements the API, it can be any arbitrary class
> bugfix(assert): Makes objectAt less restrictive

- addon/components/vertical-collection/component.js
- tests/helpers/array.js
- tests/integration/mutation-test.js
If you had a list of items `[1, 2, 3, 4, 5]` and it was changed to `[1,
4, 3, 2, 5]`, `vertical-collection` would continue to render the items
in their original position.  
This fixes the bug as discussed with @pzuraq on the Ember Slack.
> bugfix(mutation): Handle scenario where items change position

- addon/-private/data-view/radar/radar.js
I have an issue in VC usage that the container height is 0 at the beginning (because of height 100%) but will be updated later on. When the container height is 0, both `visibleTop` and `_scrollContainerHeight` are 0 and hence `visibleBottom` is -1. This crashes the app because the skip list expects item index to be non-negative. 
The fix is to set `visibleBottom` to be 0 when both `visibleTop` and `_scrollContainerHeight` are 0.
@pzuraq @runspired
> Add 0 checking for visible top & container height

- addon/-private/data-view/radar/radar.js
Sometimes while scrolling a list in a table, I see some open empty space at the top and bottom of the list (see image). After opening the inspection tab, I see height of `occluded-content` is non-zero even though there is no item before/after the list. 
Debugging in the code reveals that the occluded content style height is set to random number when `renderedTotalBefore` is negative. 
https://github.com/html-next/vertical-collection/blob/master/addon/-private/data-view/radar/radar.js#L345 
Since `renderedTotalBefore` is a computed floating number, it's possible that it could be close to 0 and negative. This PR fixes that by using 0 value when `renderedTotalBefore` is negative.
> (bugfix): Fix incorrect occluded content height.

- addon/components/vertical-collection/component.js
I have a list of 10k items and I see in my log that the `objectAt` is called 10k time at the beginning. 
This happens because the default value of `idForFirstItem` is null (https://github.com/html-next/vertical-collection/blob/master/addon/components/vertical-collection/component.js#L75) but when we do checking logic, we check `idForFirstItem !== undefined `. This inconsistency makes the `if` condition true and the loop inside `if` is executed. This PR fixes that. 
@runspired @pzuraq
> Correct checking calculateStartingIndex

- .eslintrc.js
- addon/-private/data-view/radar/radar.js
- addon/-private/index.js
- addon/-private/utils/element/estimate-element-height.js
In javascript `parseInt (100%)` does not return NaN. It returns number 100 instead (yay javascript!).
This PR fixes the logic to get max height in radar with percentage. Since `max-height` percentage represents the maximum amount of space that an element can have relative to its parent, we should extract the `maxHeight` in pixel number from parent's relative height. 
This PR alsofixes https://github.com/html-next/vertical-collection/issues/127
@runspired @pzuraq
> (bugfix): set correct max height.

- app/initializers/vertical-collection-legacy-compat.js
- ember-cli-build.js
- index.js
- package.json
- tests/helpers/test-scenarios.js
- tests/integration/basic-test.js
- tests/integration/modern-ember-test.js
- tests/integration/recycle-test.js
- tests/integration/scroll-test.js
- yarn.lock
Uses private HTMLbars APIs in 1.11 to allow us to do `{{#vertical-collection items as |item|}}`. This is necessary for addons which don't necessarily have control over the Ember version, and can't decide which version of the API to use.
> compat(legacy) - Brings the legacy API inline with modern versions

- addon/-debug/edge-visualization/debug-mixin.js
- addon/-debug/edge-visualization/visualization.js
- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/components/vertical-collection/component.js
- addon/styles/app.css
- tests/dummy/app/routes/examples/dbmon/template.hbs
- tests/dummy/app/routes/settings/snippets/defaults.js
- tests/integration/basic-test.js
- tests/integration/measure-test.js
- tests/integration/modern-ember-test.js
- tests/integration/mutation-test.js
- tests/integration/scroll-test.js
This PR makes vertical-collection tagless by default. This is inline with the best-effort non-interventionist policy that Smoke and Mirrors has - by removing the base tag, the collection is effectively the same as an `{{each}}` in terms of structure, and has virtually no effect on the users styles.
Currently there are two common issues caused by the component having a tag:
1. Percent styles effectively can't be used for elements, as they would always be relative to the `vertical-collection` tag. This would limit the ability for users to make responsive layouts using the collection. Other styles could be affected by the presence of a the tag as well, but this is definitely the most problematic.
2. The element interferes in various layouts, such as in `table` elements where users would have …
> [BREAKING] refactor(tag): Makes vertical-collection tagless

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/utils/element/get-scaled-client-rect.js
- tests/helpers/measurement.js
- tests/index.html
- tests/integration/measure-test.js
- tests/integration/scroll-test.js
When used in a container with `transform: scale`, the collection would break due to measurements being off. For example, we would measure an item that was normally 20px to be scaled by say 10px, and then we would render the measured value, which would be scaled again down to 5px. Lots of small bugs popped up due to this.
This PR adds a `getScaledClientRect` helper which accepts a scale value and element and returns the client rect scaled to the correct size. We determine the scale value in `updateConstants` by comparing the client rect of the scroll container to it's offsetHeight.
This strategy does not account for cases where, for instance, the item container is scaled, but the scroll container isn't. We can probably guard against these cases in debug assertions.
> feat(scaling): Makes the collection work with scaling

- addon/-private/utils/element/estimate-element-height.js
- tests/integration/measurement-unit-test.js
The correct root element for rem based calculations is `document.documentElement`. Logically this makes sense, it allows us to set the root element to something like `10px` and then set the body to `14px` or another standard value. In testing rem based styles were being applied to items and getting multiplied by 10px, so I dived in and found this discrepancy.
> bugfix(rem): Use the correct root element for rem based calculations

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/radar/static-radar.js
- addon/-private/data-view/skip-list.js
- addon/-private/data-view/utils/insert-range-before.js
- addon/-private/data-view/virtual-component.js
- index.js
- package.json
- tests/acceptance/acceptance-tests/record-array-test.js
- tests/dummy/app/lib/get-numbers.js
- tests/dummy/app/routes/components/number-slide/component.js
- tests/dummy/app/routes/examples/flexible-layout/template.hbs
- tests/helpers/test-scenarios.js
- tests/integration/basic-test.js
- tests/integration/measure-test.js
- tests/integration/mutation-test.js
- tests/integration/scroll-test.js
- yarn.lock
This PR returns vertical-collection to a dynamic component pool, adding and removing components from the DOM as necessary based on actual component measurements. The goal is that we never render more items than we need to, allowing the collection to respond to varying sizes of items (e.g. items that are much larger or smaller than the estimate height).
The last time this strategy was attempted it was reverted due to being a performance regression. Destroying and re-creating components dynamically cost too much compared to the benefits. This time we're getting around that issue by never actually destroying any components. We simply remove their DOM, appending it to a temporary container element and then re-appending it when we need another component.
An additional feature required to make …
> feat(dynamic-pool): Implements a dynamic component pool with incremental render

- package.json
This should fix the issue of `checker.assertAbove is not a function`.
> Move ember-cli-version-checker to deps

- addon/-private/data-view/radar/dynamic-radar.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/utils/mutation-checkers.js
- addon/components/vertical-collection/component.js
- tests/integration/scroll-test.js
Pulls the prepend/append/reset logic into Radar due to issues with
timing guarantees. This guaratees that we will check the state of the
array when we are going to update, not when we are scheduling the
change. In certain edge cases, updates to the array can occur between
when the computed property is calculated and the Radar actually updates.
> bugfix(timing): Pulls prepend/append logic into Radar

- addon/-debug/edge-visualization/debug-mixin.js
- addon/-debug/edge-visualization/visualization.js
- addon/-private/data-view/radar/radar.js
- addon/-private/data-view/viewport-container.js
- addon/-private/index.js
Rename to clarify the purpose of this class. In memory debugging and
elsewhere the name can clash with other more general classes, such as
Ember's DI container.
Fixes #163
> refactor(container): Rename Container to ViewportContainer

- index.js
`this._super` is not called correctly and can lead to error like this:
```
ctjhoa@gits ..rc/main/webapp/static/jscripts/app-cli (git)-[CPM-1050] % ember serve
WARNING: WARNING: Node v6.10.3 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
this._super is not a function
TypeError: this._super is not a function
at Class.treeForAddon (/home/ctjhoa/workspace/Negotiation-App/src/main/webapp/static/jscripts/app-cli/node_modules/ember-light-table/node_modules/@html-next/vertical-collection/index.js:64:36)
at Class._treeFor (/home/ctjhoa/workspace/Negotiation-App/src/main/webapp/static/jscripts/app-cli/node_modules/ember- …
```
> Fix treeForAddon super call

- index.js
"find host" loop breaks import functionality with latest versions of Ember CLI. [It is a part of `app.import`](https://github.com/ember-cli/ember-cli/blob/v3.0.0-beta.2/lib/models/addon.js#L675) now and no longer needed here.
> Remove "find host" loop

- addon/-private/data-view/radar/radar.js
Fixes #74
Caused Error: "TypeError: Unable to get property 'source' of undefined or null reference" (in meta.js)
As discussed in the issue, changing the code to only set `this.__ember_meta__` when in an older version of ember is found. Also changed it to `undefined` instead of `null` so the comparison in Ember meta.js file will catch it when it is unset.
> Bugfix - Fix issue where IE crashed trying to set source of a null reference

- addon/-private/data-view/radar/radar.js
- addon/components/vertical-collection/component.js
- addon/styles/app.css
- tests/integration/a11y-test.js
- tests/integration/basic-test.js
- yarn.lock
Allow user to specify custom occluded tag through `occlusionTagName` field. This allows component like table to comply with table semantics.
> API to specify custom occluded content tag

- index.js
ember-cli no longer requires the modules directory to be used and will deprecate it soon.
cc @kellyselden
> Remove use of `modules` directory for ember-cli >= 3.0

- README.md
- removed funding section because `Pledgie has closed` and donations no longer seem to work
- update branch info as `develop` branch does not exist and merged PRs were based on master
> minor update to README.MD

- addon/-private/data-view/elements/occluded-content.js
- addon/-private/data-view/elements/virtual-component.js
- package.json
bring `ember-compatibility-helpers` up to date to avoid `dependency-lint` errors
> upgrade compatibility-helpers to 1.0.0

- README.md
Document `registerWaiter` so consumers can find how to fix their `vertical-collection` tests that are failing due to updates
> Document registerWaiter. Closes #231

- .travis.yml
- package.json
> chore: use Node 8 as default

- package.json
- tests/dummy/app/routes/acceptance-tests/record-array/template.hbs
- tests/dummy/app/routes/components/number-slide/component.js
- tests/dummy/app/routes/components/number-slide/template.hbs
- tests/helpers/test-scenarios.js
- yarn.lock
- Use assign from ember-assign-polyfill instead of Ember.merge
This will remove many deprecation warnings raised in the test environment. It seems like it makes Travis fail to read the result of the tests otherwise.
- Rename index to itemIndex in `number-slide`
I haven't tracked down the problem but it seems like Ember thinks that
`{{index}}` inside the `number-slide` component is not the property but the template
for the `index` route.
I doubt this is a bug with `vertical-collection`.
> [CHORE] Fix the build

- .github/workflows/ci.yml
- addon/-private/data-view/elements/occluded-content.js
- addon/-private/data-view/elements/virtual-component.js
- config/ember-try.js
- package.json
- tests/dummy/config/optional-features.json
- yarn.lock
`master` of the vertical-collection repo had some Ember-pre-3.x
compatibility stuff removed back in 2019. For example:
* https://github.com/html-next/vertical-collection/commit/011d9a48272e80cf8e76df9be383244615597a09
Restore one of those changes.
> Restore support for Ember 2.x

- addon/styles/app.css
This was creating an issue with an autoprefixer in an engine where it added a prefix to the empty string after the comma, giving an element whose name matched the prefix the table .occluded-content properties
> Remove comma in selector list in css

- .github/workflows/ci.yml
- bin/run-tests-with-retry.sh
The retry script was incorrectly adjusting the max attempts, correct it and set the attempt count at 3.
> Extend timeout for base tests, tweak retry

- addon/-private/data-view/radar/radar.js
Commit for the below issue.
- shouldRecycle=false breaks UI when scrolling the elements fast.
Issue#296
Reference: https://github.com/html-next/vertical-collection/issues/296
> shouldRecycle=false breaks UI when scrolling the elements fast. Issue#296

- .github/workflows/ci.yml
Tests seem to rarely finish if they go over 8ish minutes. Lower the timeout.
> Lower the timeout for test

- addon/-private/data-view/radar/radar.js
- tests/acceptance/acceptance-tests/record-array-test.js
- tests/dummy/app/adapters/application.js
- tests/dummy/app/models/number-item.js
- tests/dummy/app/routes/acceptance-tests/record-array/controller.js
- tests/dummy/app/routes/acceptance-tests/record-array/template.hbs
Issue - https://github.com/html-next/vertical-collection/issues/357
See [test updating deleted elements](https://github.com/html-next/vertical-collection/pull/358/commits/39571e5d519c963d161819dd92d19a3bf964a273) commit to reproduce the issue in tests
**Description**:
The radar has a domPool virtual element to save temporarily deleted nodes and reuse them when a new item is added. So if the item is deleted from the items list the item's node can still exist in the virtual dom so the item's component can be still updated by Ember.
This behavior isn't working for computed fields on the ember models. Ember rejects the error when trying to access the computed property on the destroyed object if it hasn't been consumed before. This is possible if the items' component should render more fields …
> Delete virtual element

- .github/workflows/ci.yml
- ember-cli-build.js
- index.js
tests will also catch regressions now that the flag is set to be on for our own builds. This is a non-breaking change and can be released as a patch.
> fix: enable parallel builds

- .github/workflows/ci.yml
There is something in the vertical collection test suite which periodically hangs the action runner. Extending the timeout to 15 minutes doesn't make it more likely we get a green build, instead it increases the delay you need to wait before retrying.
Relates to #382
> Lower a CI timeout back to 9 minutes

- bin/run-tests-with-retry.sh
The retry script was previously not explicit about exiting with the status of the passed command execution. Make it so.
Should be harmless at worst.
> Add explicit exit to retry

- README.md
- addon/components/vertical-collection/component.js
- tests/dummy/app/routes/acceptance-tests/record-array/template.hbs
- tests/dummy/app/routes/examples/dbmon/template.hbs
- tests/dummy/app/routes/examples/flexible-layout/template.hbs
- tests/dummy/app/routes/examples/infinite-scroll/template.hbs
- tests/dummy/app/routes/examples/reduce-debug/template.hbs
- tests/dummy/app/routes/examples/scrollable-body/template.hbs
- tests/dummy/app/routes/settings/snippets/defaults.js
- tests/dummy/app/routes/settings/template.hbs
- tests/helpers/test-scenarios.js
- tests/integration/basic-test.js
- tests/integration/measure-test.js
- tests/integration/measurement-unit-test.js
- tests/integration/modern-ember-test.js
- tests/integration/recycle-test.js
- tests/integration/scroll-test.js
- tests/test-helper.js
* Migrate to angle bracket invocation. This is supported natively in Ember 3.12, so should be a safe and good thing to do.
* Update the readme with the 4.x range
* Drop the position param argument for `items=`. This is a breaking change ahead of 4.0.
> Adopt angle bracket invocation, update readme, drop positional param

- addon/-private/data-view/radar/radar.js
- tests/acceptance/acceptance-tests/record-array-test.js
- tests/dummy/app/routes/acceptance-tests/record-array/controller.js
- tests/dummy/app/routes/acceptance-tests/record-array/template.hbs
Insert the virtual component bound back to make sure Glimmer is not confused about the state of the DOM resulting in `DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
I was unable to add a failing test for this but I have added a few test cases to improve test coverage and verified the fix in a consuming application.
> Fix for detached Node element exception

- addon/components/vertical-collection/component.js
- tests/acceptance/acceptance-tests/record-array-test.js
- tests/dummy/app/routes/acceptance-tests/record-array/controller.js
- tests/dummy/app/routes/acceptance-tests/record-array/template.hbs
Fixes https://github.com/html-next/vertical-collection/issues/317. Similar https://github.com/html-next/vertical-collection/pull/359 but using another approach + tests
Scheduled actions as the name says are fired with delay after the render is finished. They are going through the `sync` queue (`scheduleUpdate` method) and the `measure` queue (`update` method) in the radar class and `setTimeout` (`_scheduleSendAction` method) in the component. So there is some gap after the render is finished and before the event is actually fired when the `items` argument can be changed and the event will be fired with an exception. The scheduled actions include the event and index of the item, but due to timeout, the actual item may not exist for this index. 
Clear the timeout and the queue before …
> clear scheduled actions after recalculation

- index.js
Fixes #393.
...or at least attempts to!
> Fix build for 4.0

- package.json
- yarn.lock
`master` CI fails due to some package now requiring Node 18. Resolve this by bumping the dev-pinned Node version to 18. Additionally reroll the lockfile.
> Bump dev Node to v18, reroll lockfile

- vertical-collection/addon/-private/data-view/utils/scroll-handler.js
The ScrollHandler has a bug where if multiple VerticalCollections are present in the same scrolling element, the polling behavior is started, even if passive event listeners are available. In this situation, both the listener and the polling are enabled, which probably results in some weird interactions. We noticed this issue in integration tests, because the polling does not play nice with the RAF test waiter (the tests hang forever).
The `if/else` branching made it easier to miss this bug, but the intention was most likely to only add the listener once, and only if passive listeners are available.
I'm not sure if any tests are warranted for this fix and to be honest I'm not really familiar with Embroider addons 😅 I fixed this in 4.0.2 on our fork and I'm porting the fix upstream so the …
> Fix incorrect polling start
