html-next/vertical-collection

addon/-debug/edge-visualization/debug-mixin.js
tests/dummy/app/routes/examples/dbmon/components/dbmon-row/component.js
tests/dummy/app/routes/examples/infinite-scroll/template.hbs

Some small things I noticed as I was looking through the dummy application.
Hope this helps!

fix(demo): Small fixes in dummy app

---

addon/-private/data-view/radar/dynamic-radar.js
addon/-private/data-view/radar/index.js
addon/components/vertical-collection/component.js
tests/integration/components/vertical-collection-test.js

Currently it's too buggy to try to track the tops of the containers with a cache, if it becomes a perf issue in the future we can tackle it then.

bugfix(caches): Removes cached values for tops

---

addon/components/vertical-collection/component.js
tests/integration/mutation-test.js

Fixes a bug where info will be deleted if the same array is set on the collection (with state changed)

bugfix(radar): Adds same array checker for radar computed

---

addon/-private/data-view/radar/dynamic-radar.js
addon/-private/data-view/radar/index.js
addon/styles/app.css
tests/dummy/app/styles/app.css
tests/helpers/measurement.js
tests/integration/measure-test.js
tests/integration/mutation-test.js
tests/integration/scroll-test.js

Replaces padding with margin so it works in tables.

bugfix(tables): Replaces padding with margin

---

README.md

docs(readme): fixed install link

docs(readme): fixed install link

---

addon/components/vertical-collection/component.js
addon/components/vertical-collection/template.hbs
tests/integration/basic-test.js
tests/integration/modern-ember-test.js

Remove surrounding #each div

---

addon/-private/data-view/radar/index.js
addon/-private/data-view/skip-list.js
tests/helpers/test-scenarios.js
tests/integration/mutation-test.js

Adds a helper that allows us to run the same test against multiple scenarios and strategies (static vs dynamic)

chore(tests): Adds a testScenario helper

---

addon/-private/data-view/radar/dynamic-radar.js
tests/helpers/test-scenarios.js
tests/integration/mutation-test.js
tests/integration/scroll-test.js

Uses the new testScenarios helper to clean up scroll tests. Also fixes some bugs.

cleanup(tests): Cleans up the scroll tests

---

addon/-private/data-view/virtual-component.js
config/ember-try.js
package.json
yarn.lock

Haven't actually worked with fastboot in an addon before. The experience left me very underwhelmed :'(
That said, while we don't render anything in the collection. We don't seem to break rendering everything else.

tested fastboot, fastboot itself is broken, but we are fine now

---

addon/-private/data-view/radar/dynamic-radar.js
tests/dummy/app/routes/components/number-slide/component.js

Still need to figure out what expected behavior is for enabling % heights etc.

make resize demo fail if needed

---

config/ember-try.js
tests/dummy/app/adapters/application.js
tests/dummy/app/serializers/application.js

bugfix(ember-try): Makes ember-cli-fastboot dependency null

---

addon/-private/data-view/radar/radar.js
addon/components/vertical-collection/component.js

@runspired significantly simplifies action sending, and I think divides up responsibilities better. `Radar` is still responsible for deciding when an action should be sent, and the component decides whether or not a Timeout should be scheduled at all, and loads the actual object/key within the timeout (deferring the work as much as possible). 
I think we can also make the function scheduled within `_scheduleSendAction` a static function instead of anonymous, if that would be better.

refactor(actions): Simplifies action sending

---

index.js
package.json

Fixes #100 
We'll add the debug docs back when the visual debugger is actually fixed.

chore(docs): Removes the debug message from CLI

---

addon/-private/data-view/radar/dynamic-radar.js
addon/-private/data-view/radar/radar.js
addon/-private/data-view/skip-list.js
addon/-private/data-view/utils/round-to.js
addon/-private/data-view/virtual-component.js
tests/helpers/test-scenarios.js
tests/integration/modern-ember-test.js

Swaps out the range based measurement strategy for one that measures elements. This means that all content _must_ be wrapped in top level elements. Also includes some test cleanup so they'll run in IE (we need to get cross browser automated tests going).

bugfix(M$): Fixes measurement in Microsoft browsers

---

addon/-private/data-view/radar/dynamic-radar.js
addon/-private/data-view/radar/radar.js
addon/-private/data-view/radar/static-radar.js
addon/components/vertical-collection/component.js
tests/dummy/app/routes/examples/infinite-scroll/controller.js
tests/helpers/test-scenarios.js
tests/integration/basic-test.js
tests/integration/scroll-test.js

Adds a `renderAll` flag which renders all of the items when set to `true`

feat(a11y): Adds renderAll feature

---

addon/-debug/edge-visualization/debug-mixin.js
addon/-debug/edge-visualization/visualization.js
addon/-private/data-view/radar/radar.js
index.js
tests/helpers/test-scenarios.js
tests/integration/debug-test.js
tests/test-helper.js
vendor/debug.css

Fixes the visual debugger and CSS debugger, and makes them more performant. Also updates the debug flag to `debugVis` so that it's more clear what's being turned on.
Only has tests for the `debugVis` feature, can't figure out a simple way to test debugCSS because it's all assertions. No way to try/catch async stuff.

bugfix(debug): Fixes the debug features

---

tests/integration/basic-test.js

Fixes #69 
Adds a test that verifies the collection works correctly when it starts offscreen.

test(offscreen): Adds test for starting offscreen

---

addon/-private/data-view/radar/radar.js

Check null for _debugDidUpdate

---

package.json
yarn.lock

updates ember-source to 2.15 to ensure that our demo by default is running the latest goodness :)

update ember to 2.15

---

addon/components/vertical-collection/component.js

Fixes #139
@pzuraq Please review

(bugfix): condition check on teardown

---

README.md
addon/components/vertical-collection/component.js

Please lmk where you think improvements could be made.
Also I need help with : https://github.com/html-next/vertical-collection/pull/142/files#diff-dd82fd2ab5100320f9dd5248149349efR76

Docs for Vertical Collection Component & README

---

README.md

README: Fix section headers

---

.travis.yml
addon/-private/data-view/radar/dynamic-radar.js
addon/-private/data-view/radar/radar.js

`_updateConstants` should be called before `_measure` in `_shouldScheduleRerender` to get correct container height.

Update constants before measure

---

addon/-private/data-view/radar/radar.js
tests/integration/measure-test.js
yarn.lock

We had a test which never actually ran due to a paren mismatch.
An update in a separate dependency caused a failure on master,
this PR fixes the test and makes a change to ensure the behavior
is correct.

bugfix(measure): Fix faulty test

---

addon/components/vertical-collection/template.hbs

Had to revert the template in the last PR and then ended up undoing
this change as well. _Should_ be the last fix.

[bugfix] Fix Fastboot one last time

---

.github/workflows/ci.yml
README.md
config/ember-try.js
package.json
yarn.lock

Just update CI to match what this release supports.

Update CI for vertical-collection v2

---

bin/run-tests-with-retry.sh

In dropping retries to 3, CI seems to have dropped in reliability. Creep it back up.

4 retries on CI, 1s sleep

---

addon/-debug/edge-visualization/debug-mixin.js
addon/-private/data-view/radar/radar.js
addon/components/vertical-collection/component.js
tests/dummy/app/models/number-item.js
tests/dummy/app/routes/acceptance-tests/record-array/controller.js
tests/dummy/app/routes/acceptance-tests/record-array/route.js
tests/dummy/app/routes/components/number-slide/component.js
tests/dummy/app/routes/examples/dbmon/components/dbmon-row/component.js
tests/dummy/app/routes/examples/infinite-scroll/controller.js
tests/dummy/app/routes/examples/reduce-debug/controller.js
tests/helpers/array.js
tests/integration/mutation-test.js

Adopt native getters ahead of a v4 release which only supports Ember 3.12+.

Adopt native getters over this.get

---

pnpm-lock.yaml
vertical-collection/addon/components/vertical-collection/component.js
vertical-collection/index.js
vertical-collection/package.json

We can't have any of this for v2 addon conversion anyway, and rollup will do the bundling of the private file for us anyway.
Removing this reduces the package.json delta when moving to v2 and also means we can more readily just delete the node-index.js

Remove V1 Add complexity in the index.js
